export const CATALOG_SEED = [
  ['claude', 'Claude', 'Anthropic', 'writing', 'https://claude.ai'],
  ['gpt', 'GPT-5', 'OpenAI', 'writing', 'https://chatgpt.com'],
  ['gemini', 'Gemini', 'Google', 'productivity', 'https://gemini.google.com'],
  ['llama', 'Llama', 'Meta', 'coding', 'https://llama.meta.com'],
  ['mistral', 'Mistral', 'Mistral AI', 'coding', 'https://mistral.ai'],
  ['grok', 'Grok', 'xAI', 'research', 'https://x.ai/grok'],
  ['perplexity', 'Perplexity', 'Research', 'research', 'https://www.perplexity.ai'],
  ['deepseek', 'DeepSeek', 'DeepSeek AI', 'coding', 'https://www.deepseek.com'],
  ['cohere', 'Command', 'Cohere', 'business', 'https://cohere.com'],
  ['ms-copilot', 'Copilot', 'Microsoft', 'productivity', 'https://copilot.microsoft.com'],
  ['gh-copilot', 'GitHub Copilot', 'GitHub', 'coding', 'https://github.com/features/copilot'],
  ['cursor', 'Cursor', 'Anysphere', 'coding', 'https://cursor.com'],
  ['windsurf', 'Windsurf', 'Windsurf', 'coding', 'https://windsurf.com'],
  ['zed', 'Zed', 'Zed Industries', 'coding', 'https://zed.dev'],
  ['notion-ai', 'Notion AI', 'Notion', 'productivity', 'https://www.notion.com/product/ai'],
  ['notebooklm', 'NotebookLM', 'Google', 'research', 'https://notebooklm.google'],
  ['elicit', 'Elicit', 'Research', 'research', 'https://elicit.com'],
  ['consensus', 'Consensus', 'Research', 'research', 'https://consensus.app'],
  ['scite', 'Scite', 'Research', 'research', 'https://scite.ai'],
  ['semantic-scholar', 'Semantic Scholar', 'AI2', 'research', 'https://www.semanticscholar.org'],
  ['researchrabbit', 'ResearchRabbit', 'Research', 'research', 'https://www.researchrabbit.ai'],
  ['scholarcy', 'Scholarcy', 'Research', 'research', 'https://www.scholarcy.com'],
  ['explainpaper', 'Explainpaper', 'Research', 'education', 'https://www.explainpaper.com'],
  ['humata', 'Humata', 'Docs AI', 'productivity', 'https://www.humata.ai'],
  ['chatpdf', 'ChatPDF', 'Docs AI', 'productivity', 'https://www.chatpdf.com'],
  ['otter', 'Otter.ai', 'Meetings', 'productivity', 'https://otter.ai'],
  ['fireflies', 'Fireflies', 'Meetings', 'productivity', 'https://fireflies.ai'],
  ['jasper', 'Jasper', 'Writing', 'marketing', 'https://www.jasper.ai'],
  ['copyai', 'Copy.ai', 'Writing', 'marketing', 'https://www.copy.ai'],
  ['writesonic', 'Writesonic', 'Writing', 'marketing', 'https://writesonic.com'],
  ['grammarly', 'Grammarly', 'Writing', 'writing', 'https://www.grammarly.com'],
  ['deepl', 'DeepL', 'Translation', 'writing', 'https://www.deepl.com'],
  ['midjourney', 'Midjourney', 'Midjourney', 'image', 'https://www.midjourney.com'],
  ['dalle', 'DALL-E', 'OpenAI', 'image', 'https://chatgpt.com'],
  ['stable-diffusion', 'Stable Diffusion', 'Stability AI', 'image', 'https://stability.ai'],
  ['runway', 'Runway', 'Video', 'video', 'https://runwayml.com'],
  ['elevenlabs', 'ElevenLabs', 'Voice', 'voice', 'https://elevenlabs.io'],
  ['synthesia', 'Synthesia', 'Video', 'video', 'https://www.synthesia.io'],
  ['zapier-ai', 'Zapier AI', 'Automation', 'automation', 'https://zapier.com/ai'],
  ['glean', 'Glean', 'Workspace search', 'business', 'https://www.glean.com'],
  ['harvey', 'Harvey', 'Legal AI', 'business', 'https://www.harvey.ai'],
  ['you', 'You.com', 'Search AI', 'research', 'https://you.com'],
  ['poe', 'Poe', 'Quora', 'productivity', 'https://poe.com'],
  ['claude-code', 'Claude Code', 'Anthropic', 'coding', 'https://claude.com/product/claude-code'],
  ['suno', 'Suno', 'Music', 'music', 'https://suno.com'],
  ['uizard', 'Uizard', 'App design', 'design', 'https://uizard.io']
];
